# Generated by Django 4.2.6 on 2024-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymemento_app', '0002_alter_memento_audio_alter_memento_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memento',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
